// JavaScript Document
var danhsach =[];
var ds1 ={id:"CA-HK-001",tensp:"Camera Dome hồng ngoại Hikvision",loaisp:"Camera",thuocdm:"CAMERA ANALOG",gia:"720000",img:"img/CA-HK.jpg"};
var ds2 ={id:"DA-HK-001",tensp:"Đầu ghi hình 8 Turbo HD 3.0 DVR Hikvision",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI ANALOG",gia:"4300000",img:"img/DA-HK.gif"};
var ds3 ={id:"CA-KB-001",tensp:"Camera ban đêm có màu Kbvision",loaisp:"Camera",thuocdm:"CAMERA ANALOG",gia:"8600000",img:"img/CA-KB.png"};
var ds4 ={id:"DA-KB-001",tensp:"Đầu ghi hình 32 kênh 2.0MP HDCVI Kbvision",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI ANALOG",gia:"9200000",img:"img/DA-KB.png"};
var ds5 ={id:"CA-DH-001",tensp:"Camera thân dài Dahua",loaisp:"Camera",thuocdm:"CAMERA ANALOG",gia:"1300000",img:"img/CA-DH.jpg"};
var ds6 ={id:"DA-DH-001",tensp:"Đầu ghi hình 16 kênh Dahua",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI ANALOG",gia:"9200000",img:"img/DA-DH.jpg"};
var ds7 ={id:"CA-VT-001",tensp:"Camera chống cháy nổ 1000TVL Vantech",loaisp:"Camera",thuocdm:"CAMERA ANALOG",gia:"39800000",img:"img/CA-VT.jpg"};
var ds8 ={id:"DA-VT-001",tensp:"Đầu ghi hình 4 kênh Vantech",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI ANALOG",gia:"3900000",img:"img/DA-VT.jpg"};
var ds9 ={id:"CI-AV-001",tensp:"Camera IP Speed Dome hồng ngoại Avtech",loaisp:"Camera",thuocdm:"CAMERA IP",gia:"7025000",img:"img/CI-AV.jpg"};
var ds10 ={id:"DI-AV-001",tensp:"Đầu ghi hình camera IP 16 kênh Avtech",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI IP",gia:"12740000",img:"img/DI-AV.jpg"};
var ds11 ={id:"CI-AV-003",tensp:"Camera IP thân hồng ngoại Vantech",loaisp:"Camera",thuocdm:"CAMERA IP",gia:"4200000",img:"img/CI-VT.jpg"};
var ds12 ={id:"DI-AV-003",tensp:"Đầu ghi hình HDI 16 kênh Vantech",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI IP",gia:"25000000",img:"img/CA-DH.jpg"};

var ds13 ={id:"CA-HK-002",tensp:"Camera thân HDVI Hikvision",loaisp:"Camera",thuocdm:"CAMERA ANALOG",gia:"1870000",img:"img/CA-HK.jpg"};
var ds14 ={id:"DA-HK-002",tensp:"Đầu ghi 4 kênh Tourbo HD 3.0 Hikvision",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI ANALOG",gia:"4880000",img:"img/DA-HK.gif"};
var ds15 ={id:"CA-KB-002",tensp:"Camera dome HDCVI Kbvision",loaisp:"Camera",thuocdm:"CAMERA ANALOG",gia:"900000",img:"img/CA-KB.png"};
var ds16 ={id:"DA-KB-002",tensp:"Đầu ghi hình 16 kênh full HD hỗn hợp Kbvision",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI ANALOG",gia:"12500000",img:"img/DA-KB.png"};
var ds17 ={id:"CA-DH-002",tensp:"Camera thân dài HDCVI Dahua",loaisp:"Camera",thuocdm:"CAMERA ANALOG",gia:"1120000",img:"img/CA-DH.jpg"};
var ds18 ={id:"DA-DH-002",tensp:"Đầu ghi hình 8 kênh Dahua",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI ANALOG",gia:"4900000",img:"img/DA-DH.jpg"};
var ds19 ={id:"CA-VT-002",tensp:"Camera thân hồng ngoại Vantech",loaisp:"Camera",thuocdm:"CAMERA ANALOG",gia:"6656000",img:"img/CA-VT.jpg"};
var ds20 ={id:"DA-VT-002",tensp:"Đầu ghi hình 4 kênh Vantech",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI ANALOG",gia:"20900000",img:"img/DA-VT.jpg"};
var ds21 ={id:"CI-AV-002",tensp:"Camera IP thân hồng ngoại Avtech",loaisp:"Camera",thuocdm:"CAMERA IP",gia:"2600000",img:"img/CI-AV.jpg"};
var ds22 ={id:"DI-AV-002",tensp:"Đầu ghi hình HDI 16 kênh Avtech",loaisp:"Đầu ghi",thuocdm:"ĐẦU GHI IP",gia:"34800000",img:"img/DI-AV.jpg"};

danhsach.push(ds1);
danhsach.push(ds2);
danhsach.push(ds3);
danhsach.push(ds4);
danhsach.push(ds5);
danhsach.push(ds6);
danhsach.push(ds7);
danhsach.push(ds8);
danhsach.push(ds9);
danhsach.push(ds10);
danhsach.push(ds11);
danhsach.push(ds12);
danhsach.push(ds13);
danhsach.push(ds14);
danhsach.push(ds15);
danhsach.push(ds16);
danhsach.push(ds17);
danhsach.push(ds18);
danhsach.push(ds19);
danhsach.push(ds20);
danhsach.push(ds21);
danhsach.push(ds22);